name: release
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
jobs:
  release:
    name: Release awscccli
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        env:
          GO111MODULE: on
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          version: latest
          args: release --rm-dist
